# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: 875423353@qq.com
baseurl: /
domain: yz53665.github.io
url: https://yz53665.github.io
github_username: yz53665

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

# Dependencies
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               QRQ's Blog
tagline:             '生命不息，折腾不止'
description:         '自动化 | 模式识别 | 图像处理'
paginate:            7

# About/contact
author:
  name:              QRQ
  url:               https://github.com/yz53665
  email:             875423353@qq.com

# Custom vars
version:             2.0

# Social Media
github:				https://github.com/yz53665
disqus:             qrqBlog

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/